# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# Through which shell command hooks will run. The command will be replaced in '{}'
shell = "fish -c '{}'"

[[items]]
file = "~/.config/eww/colors.scss"
template = "styles"
subtemplate = "scss"
hook = "eww reload"
rewrite = true
# # Whether this hook should be executed when flavours is ran with lightweight flag
light = false

[[item]]
file = "~/.config/nvim/colors/base16.vim"
template = "vim"
rewrite = true
hook = "reloadnvim"

[[item]]
file = "~/.config/alacritty/alacritty.toml"
template = "alacritty"
subtemplate = "default-256"

[[item]]
file = "~/.config/hypr/hyprland.conf.d/colors.conf"
rewrite = true
template = "hypr"
subtemplate = "hyprland-conf"

# Example file. For sway, waybar and (beautiful)discord. Runs hooks through bash:

# shell = "bash -c '{}'"
#
# [[items]]
# file = "~/.config/sway/config"
# template = "sway"
# subtemplate = "colors"
# hook = "swaymsg reload"
# light = false
#
# [[items]]
# file = "~/.config/waybar/colors.css"
# template = "waybar"
# rewrite = true
# 
# [[items]]
# file = "~/.config/beautifuldiscord/style.css"
# template = "styles"
# subtemplate = "css-variables"
# start= "/* Start flavours */"
# end = "/* End flavours */"
