[font]
builtin_box_drawing = true
size = 11.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Blex Mono Nerd Font"
style = "Regular"

[window.class]
general = "terminal"
instance = "Alacritty"
